batch_size: 32
workers: 2
nepoch: 400
model_name: PointAttN
load_model: null  # <--- ИЗМЕНЕНО: чтобы учить с нуля
start_epoch: 0
num_points: 2048  # <--- Проверьте, совпадает ли это с вашим 'partial' в h5
work_dir: log/
flag: debug
loss: cd
manual_seed: null
step_interval_to_print: 50 # <--- Можно уменьшить для наглядности
epoch_interval_to_save: 1
epoch_interval_to_val: 1

lr: 0.0001
lr_decay: True
lr_decay_interval: 40
lr_decay_rate: 0.7
lr_step_decay_epochs: null
lr_step_decay_rates: null
lr_clip: 1.e-6
optimizer: Adam
weight_decay: 0
betas: 0.9, 0.999

device: '0'
dataset: 'custom'
# Пути ниже можно оставить, они будут игнорироваться
pcnpath: $PATH/ShapeNetCompletion
c3dpath: $PATH/shapenet
save_vis: False
